import { CliSettingCatalogItem } from "./types";

export const macosCliSettingsCatalog: CliSettingCatalogItem[] = [
  {
    id: "finder.show-full-posix-path-title",
    title: "Show full POSIX path in Finder title",
    category: "Finder",
    tool: "defaults",
    commands: {
      read: "defaults read com.apple.finder _FXShowPosixPathInTitle",
      set: "defaults write com.apple.finder _FXShowPosixPathInTitle -bool {{enabled}}",
      reset: "defaults delete com.apple.finder _FXShowPosixPathInTitle",
    },
    applyAction: "killall Finder",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: true,
  },
  {
    id: "finder.show-path-bar",
    title: "Show path bar",
    category: "Finder",
    tool: "defaults",
    commands: {
      read: "defaults read com.apple.finder ShowPathbar",
      set: "defaults write com.apple.finder ShowPathbar -bool {{enabled}}",
      reset: "defaults delete com.apple.finder ShowPathbar",
    },
    applyAction: "killall Finder",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: true,
  },
  {
    id: "finder.show-status-bar",
    title: "Show status bar",
    category: "Finder",
    tool: "defaults",
    commands: {
      read: "defaults read com.apple.finder ShowStatusBar",
      set: "defaults write com.apple.finder ShowStatusBar -bool {{enabled}}",
      reset: "defaults delete com.apple.finder ShowStatusBar",
    },
    applyAction: "killall Finder",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: true,
  },
  {
    id: "finder.show-all-extensions",
    title: "Show all filename extensions",
    category: "Finder",
    tool: "defaults",
    commands: {
      read: "defaults read NSGlobalDomain AppleShowAllExtensions",
      set: "defaults write NSGlobalDomain AppleShowAllExtensions -bool {{enabled}}",
      reset: "defaults delete NSGlobalDomain AppleShowAllExtensions",
    },
    applyAction: "killall Finder",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: true,
  },
  {
    id: "finder.extension-change-warning",
    title: "Warn before changing extension",
    category: "Finder",
    tool: "defaults",
    commands: {
      read: "defaults read com.apple.finder FXEnableExtensionChangeWarning",
      set: "defaults write com.apple.finder FXEnableExtensionChangeWarning -bool {{enabled}}",
      reset: "defaults delete com.apple.finder FXEnableExtensionChangeWarning",
    },
    applyAction: "killall Finder",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: true,
  },
  {
    id: "finder.show-hidden-files",
    title: "Show hidden files",
    category: "Finder",
    tool: "defaults",
    commands: {
      read: "defaults read com.apple.finder AppleShowAllFiles",
      set: "defaults write com.apple.finder AppleShowAllFiles -bool {{enabled}}",
      reset: "defaults delete com.apple.finder AppleShowAllFiles",
    },
    applyAction: "killall Finder",
    requiresSudo: false,
    riskLevel: "caution",
    showInDefaultView: true,
    notes: "Hidden files include critical system files.",
  },
  {
    id: "finder.sort-folders-first",
    title: "Keep folders on top when sorting by name",
    category: "Finder",
    tool: "defaults",
    commands: {
      read: "defaults read com.apple.finder _FXSortFoldersFirst",
      set: "defaults write com.apple.finder _FXSortFoldersFirst -bool {{enabled}}",
      reset: "defaults delete com.apple.finder _FXSortFoldersFirst",
    },
    applyAction: "killall Finder",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: true,
  },
  {
    id: "finder.no-dsstore-network",
    title: "Disable .DS_Store on network volumes",
    category: "Finder",
    tool: "defaults",
    commands: {
      read: "defaults read com.apple.desktopservices DSDontWriteNetworkStores",
      set: "defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool {{enabled}}",
      reset: "defaults delete com.apple.desktopservices DSDontWriteNetworkStores",
    },
    applyAction: "killall Finder",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: false,
  },
  {
    id: "finder.no-dsstore-usb",
    title: "Disable .DS_Store on USB volumes",
    category: "Finder",
    tool: "defaults",
    commands: {
      read: "defaults read com.apple.desktopservices DSDontWriteUSBStores",
      set: "defaults write com.apple.desktopservices DSDontWriteUSBStores -bool {{enabled}}",
      reset: "defaults delete com.apple.desktopservices DSDontWriteUSBStores",
    },
    applyAction: "killall Finder",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: false,
  },
  {
    id: "dock.add-spacer-apps",
    title: "Add spacer to app side of Dock",
    category: "Dock",
    tool: "defaults",
    commands: {
      read: "defaults read com.apple.dock persistent-apps",
      set: "defaults write com.apple.dock persistent-apps -array-add '{\"tile-type\"=\"spacer-tile\";}'",
    },
    applyAction: "killall Dock",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: false,
    notes: "No direct reset command; remove spacer from Dock manually.",
  },
  {
    id: "dock.add-spacer-others",
    title: "Add spacer to right side of Dock",
    category: "Dock",
    tool: "defaults",
    commands: {
      read: "defaults read com.apple.dock persistent-others",
      set: "defaults write com.apple.dock persistent-others -array-add '{\"tile-type\"=\"spacer-tile\";}'",
    },
    applyAction: "killall Dock",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: false,
    notes: "No direct reset command; remove spacer from Dock manually.",
  },
  {
    id: "dock.autohide-delay",
    title: "Dock auto-hide delay",
    category: "Dock",
    tool: "defaults",
    commands: {
      read: "defaults read com.apple.dock autohide-delay",
      set: "defaults write com.apple.dock autohide-delay -float {{seconds}}",
      reset: "defaults delete com.apple.dock autohide-delay",
    },
    applyAction: "killall Dock",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: true,
  },
  {
    id: "dock.autohide-time-modifier",
    title: "Dock auto-hide animation speed",
    category: "Dock",
    tool: "defaults",
    commands: {
      read: "defaults read com.apple.dock autohide-time-modifier",
      set: "defaults write com.apple.dock autohide-time-modifier -float {{seconds}}",
      reset: "defaults delete com.apple.dock autohide-time-modifier",
    },
    applyAction: "killall Dock",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: false,
  },
  {
    id: "dock.show-hidden-translucent",
    title: "Show hidden app icons as translucent",
    category: "Dock",
    tool: "defaults",
    commands: {
      read: "defaults read com.apple.dock showhidden",
      set: "defaults write com.apple.dock showhidden -bool {{enabled}}",
      reset: "defaults delete com.apple.dock showhidden",
    },
    applyAction: "killall Dock",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: true,
  },
  {
    id: "dock.disable-bouncing",
    title: "Disable bouncing app icons",
    category: "Dock",
    tool: "defaults",
    commands: {
      read: "defaults read com.apple.dock no-bouncing",
      set: "defaults write com.apple.dock no-bouncing -bool {{enabled}}",
      reset: "defaults delete com.apple.dock no-bouncing",
    },
    applyAction: "killall Dock",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: false,
    visualDemo: "dock-icon-bounce",
  },
  {
    id: "dock.spring-load-actions",
    title: "Enable spring-load actions on all Dock items",
    category: "Dock",
    tool: "defaults",
    commands: {
      read: "defaults read com.apple.dock enable-spring-load-actions-on-all-items",
      set: "defaults write com.apple.dock enable-spring-load-actions-on-all-items -bool {{enabled}}",
      reset: "defaults delete com.apple.dock enable-spring-load-actions-on-all-items",
    },
    applyAction: "killall Dock",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: false,
  },
  {
    id: "dock.show-recents",
    title: "Show recent apps in Dock",
    category: "Dock",
    tool: "defaults",
    commands: {
      read: "defaults read com.apple.dock show-recents",
      set: "defaults write com.apple.dock show-recents -bool {{enabled}}",
      reset: "defaults delete com.apple.dock show-recents",
    },
    applyAction: "killall Dock",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: true,
  },
  {
    id: "global.apple-press-and-hold",
    title: "Key hold behavior (accent menu vs repeat)",
    category: "Global UI and Input",
    tool: "defaults",
    commands: {
      read: "defaults read NSGlobalDomain ApplePressAndHoldEnabled",
      set: "defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool {{enabled}}",
      reset: "defaults delete NSGlobalDomain ApplePressAndHoldEnabled",
    },
    applyAction: "logout",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: true,
  },
  {
    id: "global.key-repeat",
    title: "Keyboard repeat speed",
    category: "Global UI and Input",
    tool: "defaults",
    commands: {
      read: "defaults read NSGlobalDomain KeyRepeat",
      set: "defaults write NSGlobalDomain KeyRepeat -int {{value}}",
      reset: "defaults delete NSGlobalDomain KeyRepeat",
    },
    applyAction: "logout",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: true,
  },
  {
    id: "global.initial-key-repeat",
    title: "Initial keyboard repeat delay",
    category: "Global UI and Input",
    tool: "defaults",
    commands: {
      read: "defaults read NSGlobalDomain InitialKeyRepeat",
      set: "defaults write NSGlobalDomain InitialKeyRepeat -int {{value}}",
      reset: "defaults delete NSGlobalDomain InitialKeyRepeat",
    },
    applyAction: "logout",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: true,
  },
  {
    id: "global.scroll-bars",
    title: "Always show scroll bars",
    category: "Global UI and Input",
    tool: "defaults",
    commands: {
      read: "defaults read NSGlobalDomain AppleShowScrollBars",
      set: "defaults write NSGlobalDomain AppleShowScrollBars -string {{mode}}",
      reset: "defaults delete NSGlobalDomain AppleShowScrollBars",
    },
    applyAction: "none",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: true,
    notes: "Use mode=Always|Automatic|WhenScrolling.",
  },
  {
    id: "global.natural-scroll",
    title: "Natural scrolling direction",
    category: "Global UI and Input",
    tool: "defaults",
    commands: {
      read: "defaults read NSGlobalDomain com.apple.swipescrolldirection",
      set: "defaults write NSGlobalDomain com.apple.swipescrolldirection -bool {{enabled}}",
      reset: "defaults delete NSGlobalDomain com.apple.swipescrolldirection",
    },
    applyAction: "none",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: true,
  },
  {
    id: "global.full-keyboard-access",
    title: "Full keyboard access mode",
    category: "Global UI and Input",
    tool: "defaults",
    commands: {
      read: "defaults read NSGlobalDomain AppleKeyboardUIMode",
      set: "defaults write NSGlobalDomain AppleKeyboardUIMode -int {{value}}",
      reset: "defaults delete NSGlobalDomain AppleKeyboardUIMode",
    },
    applyAction: "none",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: false,
    notes: "Common values: 2 or 3.",
  },
  {
    id: "global.auto-spell-correct",
    title: "Automatic spelling correction",
    category: "Global UI and Input",
    tool: "defaults",
    commands: {
      read: "defaults read NSGlobalDomain NSAutomaticSpellingCorrectionEnabled",
      set: "defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool {{enabled}}",
      reset: "defaults delete NSGlobalDomain NSAutomaticSpellingCorrectionEnabled",
    },
    applyAction: "none",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: true,
  },
  {
    id: "trackpad.tap-to-click",
    title: "Tap to click",
    category: "Trackpad and Mouse",
    tool: "defaults",
    commands: {
      read: "defaults read com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking",
      set: "defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool {{enabled}}",
      reset: "defaults delete com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking",
    },
    applyAction: "logout",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: true,
  },
  {
    id: "trackpad.tap-behavior-current-host",
    title: "Tap behavior on current host",
    category: "Trackpad and Mouse",
    tool: "defaults",
    commands: {
      read: "defaults -currentHost read NSGlobalDomain com.apple.mouse.tapBehavior",
      set: "defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int {{value}}",
      reset: "defaults -currentHost delete NSGlobalDomain com.apple.mouse.tapBehavior",
    },
    applyAction: "logout",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: false,
  },
  {
    id: "trackpad.secondary-click-corner",
    title: "Trackpad secondary click corner",
    category: "Trackpad and Mouse",
    tool: "defaults",
    commands: {
      read: "defaults read com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadCornerSecondaryClick",
      set: "defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadCornerSecondaryClick -int {{value}}",
      reset: "defaults delete com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadCornerSecondaryClick",
    },
    applyAction: "logout",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: false,
  },
  {
    id: "trackpad.right-click-enabled",
    title: "Trackpad right click",
    category: "Trackpad and Mouse",
    tool: "defaults",
    commands: {
      read: "defaults read com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadRightClick",
      set: "defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadRightClick -bool {{enabled}}",
      reset: "defaults delete com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadRightClick",
    },
    applyAction: "logout",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: true,
  },
  {
    id: "screencapture.location",
    title: "Screenshot save location",
    category: "Screenshots",
    tool: "defaults",
    commands: {
      read: "defaults read com.apple.screencapture location",
      set: "defaults write com.apple.screencapture location {{absolutePath}}",
      reset: "defaults delete com.apple.screencapture location",
    },
    applyAction: "killall SystemUIServer",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: true,
  },
  {
    id: "screencapture.type",
    title: "Screenshot file format",
    category: "Screenshots",
    tool: "defaults",
    commands: {
      read: "defaults read com.apple.screencapture type",
      set: "defaults write com.apple.screencapture type {{format}}",
      reset: "defaults delete com.apple.screencapture type",
    },
    applyAction: "killall SystemUIServer",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: true,
    notes: "Common formats: png, jpg, tiff, pdf, bmp, gif.",
  },
  {
    id: "screencapture.disable-shadow",
    title: "Disable screenshot window shadow",
    category: "Screenshots",
    tool: "defaults",
    commands: {
      read: "defaults read com.apple.screencapture disable-shadow",
      set: "defaults write com.apple.screencapture disable-shadow -bool {{enabled}}",
      reset: "defaults delete com.apple.screencapture disable-shadow",
    },
    applyAction: "killall SystemUIServer",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: true,
  },
  {
    id: "screencapture.filename-prefix",
    title: "Screenshot filename prefix",
    category: "Screenshots",
    tool: "defaults",
    commands: {
      read: "defaults read com.apple.screencapture name",
      set: "defaults write com.apple.screencapture name {{prefix}}",
      reset: "defaults delete com.apple.screencapture name",
    },
    applyAction: "killall SystemUIServer",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: false,
  },
  {
    id: "screencapture.include-date",
    title: "Include date in screenshot filename",
    category: "Screenshots",
    tool: "defaults",
    commands: {
      read: "defaults read com.apple.screencapture include-date",
      set: "defaults write com.apple.screencapture include-date -bool {{enabled}}",
      reset: "defaults delete com.apple.screencapture include-date",
    },
    applyAction: "killall SystemUIServer",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: false,
  },
  {
    id: "loginwindow.guest-enabled",
    title: "Allow Guest at login window",
    category: "Login Window",
    tool: "defaults",
    commands: {
      read: "sudo defaults read /Library/Preferences/com.apple.loginwindow GuestEnabled",
      set: "sudo defaults write /Library/Preferences/com.apple.loginwindow GuestEnabled -bool {{enabled}}",
      reset: "sudo defaults delete /Library/Preferences/com.apple.loginwindow GuestEnabled",
    },
    applyAction: "reboot",
    requiresSudo: true,
    riskLevel: "caution",
    showInDefaultView: false,
  },
  {
    id: "loginwindow.show-full-name",
    title: "Show username and password fields",
    category: "Login Window",
    tool: "defaults",
    commands: {
      read: "sudo defaults read /Library/Preferences/com.apple.loginwindow SHOWFULLNAME",
      set: "sudo defaults write /Library/Preferences/com.apple.loginwindow SHOWFULLNAME -bool {{enabled}}",
      reset: "sudo defaults delete /Library/Preferences/com.apple.loginwindow SHOWFULLNAME",
    },
    applyAction: "reboot",
    requiresSudo: true,
    riskLevel: "caution",
    showInDefaultView: false,
  },
  {
    id: "loginwindow.show-input-menu",
    title: "Show input menu at login window",
    category: "Login Window",
    tool: "defaults",
    commands: {
      read: "sudo defaults read /Library/Preferences/com.apple.loginwindow showInputMenu",
      set: "sudo defaults write /Library/Preferences/com.apple.loginwindow showInputMenu -bool {{enabled}}",
      reset: "sudo defaults delete /Library/Preferences/com.apple.loginwindow showInputMenu",
    },
    applyAction: "reboot",
    requiresSudo: true,
    riskLevel: "safe",
    showInDefaultView: false,
  },
  {
    id: "loginwindow.admin-host-info",
    title: "Login window host info display",
    category: "Login Window",
    tool: "defaults",
    commands: {
      read: "sudo defaults read /Library/Preferences/com.apple.loginwindow AdminHostInfo",
      set: "sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo -string {{value}}",
      reset: "sudo defaults delete /Library/Preferences/com.apple.loginwindow AdminHostInfo",
    },
    applyAction: "reboot",
    requiresSudo: true,
    riskLevel: "safe",
    showInDefaultView: false,
    notes: "Common values: HostName, SystemVersion, IPAddress, or empty string.",
  },
  {
    id: "loginwindow.banner-text",
    title: "Login window banner text",
    category: "Login Window",
    tool: "defaults",
    commands: {
      read: "sudo defaults read /Library/Preferences/com.apple.loginwindow LoginwindowText",
      set: "sudo defaults write /Library/Preferences/com.apple.loginwindow LoginwindowText -string {{text}}",
      reset: "sudo defaults delete /Library/Preferences/com.apple.loginwindow LoginwindowText",
    },
    applyAction: "reboot",
    requiresSudo: true,
    riskLevel: "safe",
    showInDefaultView: false,
  },
  {
    id: "pmset.displaysleep",
    title: "Display sleep timer",
    category: "Power Management",
    tool: "pmset",
    commands: {
      read: "pmset -g | grep -E '^[[:space:]]*displaysleep'",
      set: "sudo pmset -a displaysleep {{minutes}}",
    },
    applyAction: "none",
    requiresSudo: true,
    riskLevel: "safe",
    showInDefaultView: true,
  },
  {
    id: "pmset.disksleep",
    title: "Disk sleep timer",
    category: "Power Management",
    tool: "pmset",
    commands: {
      read: "pmset -g | grep -E '^[[:space:]]*disksleep'",
      set: "sudo pmset -a disksleep {{minutes}}",
    },
    applyAction: "none",
    requiresSudo: true,
    riskLevel: "safe",
    showInDefaultView: false,
  },
  {
    id: "pmset.system-sleep",
    title: "System sleep timer",
    category: "Power Management",
    tool: "pmset",
    commands: {
      read: "pmset -g | grep -E '^[[:space:]]*sleep[[:space:]]'",
      set: "sudo pmset -a sleep {{minutes}}",
    },
    applyAction: "none",
    requiresSudo: true,
    riskLevel: "caution",
    showInDefaultView: true,
  },
  {
    id: "pmset.womp",
    title: "Wake on network packet",
    category: "Power Management",
    tool: "pmset",
    commands: {
      read: "pmset -g | grep -E '^[[:space:]]*womp'",
      set: "sudo pmset -a womp {{value}}",
    },
    applyAction: "none",
    requiresSudo: true,
    riskLevel: "safe",
    showInDefaultView: false,
    notes: "Use value=0 or 1.",
  },
  {
    id: "pmset.hibernatemode",
    title: "Hibernation mode",
    category: "Power Management",
    tool: "pmset",
    commands: {
      read: "pmset -g | grep -E '^[[:space:]]*hibernatemode'",
      set: "sudo pmset -a hibernatemode {{mode}}",
    },
    applyAction: "reboot",
    requiresSudo: true,
    riskLevel: "danger",
    showInDefaultView: false,
    notes: "Common modes: 0, 3, 25. Hardware and macOS dependent.",
  },
  {
    id: "pmset.standby",
    title: "Standby mode",
    category: "Power Management",
    tool: "pmset",
    commands: {
      read: "pmset -g | grep -E '^[[:space:]]*standby[[:space:]]'",
      set: "sudo pmset -a standby {{value}}",
    },
    applyAction: "none",
    requiresSudo: true,
    riskLevel: "caution",
    showInDefaultView: false,
    notes: "Use value=0 or 1.",
  },
  {
    id: "pmset.standbydelayhigh",
    title: "Standby delay high battery",
    category: "Power Management",
    tool: "pmset",
    commands: {
      read: "pmset -g | grep -E '^[[:space:]]*standbydelayhigh'",
      set: "sudo pmset -a standbydelayhigh {{seconds}}",
    },
    applyAction: "none",
    requiresSudo: true,
    riskLevel: "caution",
    showInDefaultView: false,
  },
  {
    id: "pmset.standbydelaylow",
    title: "Standby delay low battery",
    category: "Power Management",
    tool: "pmset",
    commands: {
      read: "pmset -g | grep -E '^[[:space:]]*standbydelaylow'",
      set: "sudo pmset -a standbydelaylow {{seconds}}",
    },
    applyAction: "none",
    requiresSudo: true,
    riskLevel: "caution",
    showInDefaultView: false,
  },
  {
    id: "pmset.powernap",
    title: "Power Nap",
    category: "Power Management",
    tool: "pmset",
    commands: {
      read: "pmset -g | grep -E '^[[:space:]]*powernap'",
      set: "sudo pmset -a powernap {{value}}",
    },
    applyAction: "none",
    requiresSudo: true,
    riskLevel: "safe",
    showInDefaultView: true,
    notes: "Use value=0 or 1.",
  },
  {
    id: "pmset.tcpkeepalive",
    title: "TCP keepalive during sleep",
    category: "Power Management",
    tool: "pmset",
    commands: {
      read: "pmset -g | grep -E '^[[:space:]]*tcpkeepalive'",
      set: "sudo pmset -a tcpkeepalive {{value}}",
    },
    applyAction: "none",
    requiresSudo: true,
    riskLevel: "caution",
    showInDefaultView: false,
    notes: "Use value=0 or 1.",
  },
  {
    id: "pmset.autopoweroff",
    title: "Auto power off (AC)",
    category: "Power Management",
    tool: "pmset",
    commands: {
      read: "pmset -g | grep -E '^[[:space:]]*autopoweroff[[:space:]]'",
      set: "sudo pmset -a autopoweroff {{value}}",
    },
    applyAction: "none",
    requiresSudo: true,
    riskLevel: "caution",
    showInDefaultView: false,
    notes: "Use value=0 or 1.",
  },
  {
    id: "pmset.autopoweroffdelay",
    title: "Auto power off delay (seconds)",
    category: "Power Management",
    tool: "pmset",
    commands: {
      read: "pmset -g | grep -E '^[[:space:]]*autopoweroffdelay'",
      set: "sudo pmset -a autopoweroffdelay {{seconds}}",
    },
    applyAction: "none",
    requiresSudo: true,
    riskLevel: "caution",
    showInDefaultView: false,
  },
  {
    id: "network.dns-servers",
    title: "Set DNS servers for network service",
    category: "Network Services",
    tool: "networksetup",
    commands: {
      read: "networksetup -getdnsservers {{networkService}}",
      set: "sudo networksetup -setdnsservers {{networkService}} {{dnsList}}",
      reset: "sudo networksetup -setdnsservers {{networkService}} Empty",
    },
    applyAction: "none",
    requiresSudo: true,
    riskLevel: "caution",
    showInDefaultView: true,
    notes: "Use networkService values like Wi-Fi or Ethernet.",
  },
  {
    id: "network.search-domains",
    title: "Set DNS search domains",
    category: "Network Services",
    tool: "networksetup",
    commands: {
      read: "networksetup -getsearchdomains {{networkService}}",
      set: "sudo networksetup -setsearchdomains {{networkService}} {{domainList}}",
      reset: "sudo networksetup -setsearchdomains {{networkService}} Empty",
    },
    applyAction: "none",
    requiresSudo: true,
    riskLevel: "caution",
    showInDefaultView: false,
  },
  {
    id: "network.web-proxy-state",
    title: "Web proxy on or off",
    category: "Network Services",
    tool: "networksetup",
    commands: {
      read: "networksetup -getwebproxy {{networkService}}",
      set: "sudo networksetup -setwebproxystate {{networkService}} {{state}}",
    },
    applyAction: "none",
    requiresSudo: true,
    riskLevel: "caution",
    showInDefaultView: true,
    notes: "Use state=on or off.",
  },
  {
    id: "network.web-proxy-config",
    title: "Web proxy host and port",
    category: "Network Services",
    tool: "networksetup",
    commands: {
      read: "networksetup -getwebproxy {{networkService}}",
      set: "sudo networksetup -setwebproxy {{networkService}} {{host}} {{port}}",
      reset: "sudo networksetup -setwebproxystate {{networkService}} off",
    },
    applyAction: "none",
    requiresSudo: true,
    riskLevel: "caution",
    showInDefaultView: false,
  },
  {
    id: "network.secure-web-proxy-state",
    title: "HTTPS proxy on or off",
    category: "Network Services",
    tool: "networksetup",
    commands: {
      read: "networksetup -getsecurewebproxy {{networkService}}",
      set: "sudo networksetup -setsecurewebproxystate {{networkService}} {{state}}",
    },
    applyAction: "none",
    requiresSudo: true,
    riskLevel: "caution",
    showInDefaultView: false,
    notes: "Use state=on or off.",
  },
  {
    id: "network.socks-proxy-state",
    title: "SOCKS proxy on or off",
    category: "Network Services",
    tool: "networksetup",
    commands: {
      read: "networksetup -getsocksfirewallproxy {{networkService}}",
      set: "sudo networksetup -setsocksfirewallproxystate {{networkService}} {{state}}",
    },
    applyAction: "none",
    requiresSudo: true,
    riskLevel: "caution",
    showInDefaultView: false,
    notes: "Use state=on or off.",
  },
  {
    id: "network.ipv6-off",
    title: "Disable IPv6 for network service",
    category: "Network Services",
    tool: "networksetup",
    commands: {
      read: "networksetup -getinfo {{networkService}}",
      set: "sudo networksetup -setv6off {{networkService}}",
      reset: "sudo networksetup -setv6automatic {{networkService}}",
    },
    applyAction: "none",
    requiresSudo: true,
    riskLevel: "danger",
    showInDefaultView: false,
  },
  {
    id: "network.wifi-power",
    title: "Wi-Fi power",
    category: "Network Services",
    tool: "networksetup",
    commands: {
      read: "networksetup -getairportpower {{device}}",
      set: "sudo networksetup -setairportpower {{device}} {{state}}",
    },
    applyAction: "none",
    requiresSudo: true,
    riskLevel: "safe",
    showInDefaultView: true,
    notes: "Device is usually en0. Use state=on or off.",
  },
  {
    id: "host.computer-name",
    title: "ComputerName",
    category: "Host and Discovery",
    tool: "scutil",
    commands: {
      read: "scutil --get ComputerName",
      set: "sudo scutil --set ComputerName {{value}}",
    },
    applyAction: "none",
    requiresSudo: true,
    riskLevel: "safe",
    showInDefaultView: true,
  },
  {
    id: "host.host-name",
    title: "HostName",
    category: "Host and Discovery",
    tool: "scutil",
    commands: {
      read: "scutil --get HostName",
      set: "sudo scutil --set HostName {{value}}",
    },
    applyAction: "none",
    requiresSudo: true,
    riskLevel: "caution",
    showInDefaultView: false,
  },
  {
    id: "host.local-host-name",
    title: "LocalHostName",
    category: "Host and Discovery",
    tool: "scutil",
    commands: {
      read: "scutil --get LocalHostName",
      set: "sudo scutil --set LocalHostName {{value}}",
    },
    applyAction: "none",
    requiresSudo: true,
    riskLevel: "safe",
    showInDefaultView: false,
  },
  {
    id: "host.remote-login",
    title: "Remote Login (SSH)",
    category: "Host and Discovery",
    tool: "systemsetup",
    commands: {
      read: "systemsetup -getremotelogin",
      set: "sudo systemsetup -setremotelogin {{state}}",
    },
    applyAction: "none",
    requiresSudo: true,
    riskLevel: "caution",
    showInDefaultView: false,
    notes: "Use state=on or off.",
  },
  {
    id: "host.remote-apple-events",
    title: "Remote Apple Events",
    category: "Host and Discovery",
    tool: "systemsetup",
    commands: {
      read: "systemsetup -getremoteappleevents",
      set: "sudo systemsetup -setremoteappleevents {{state}}",
    },
    applyAction: "none",
    requiresSudo: true,
    riskLevel: "caution",
    showInDefaultView: false,
    notes: "Use state=on or off.",
  },
  {
    id: "host.timezone",
    title: "System timezone",
    category: "Host and Discovery",
    tool: "systemsetup",
    commands: {
      read: "systemsetup -gettimezone",
      set: "sudo systemsetup -settimezone {{timezone}}",
    },
    applyAction: "none",
    requiresSudo: true,
    riskLevel: "safe",
    showInDefaultView: true,
  },
  {
    id: "spotlight.indexing-toggle",
    title: "Spotlight indexing state",
    category: "Spotlight",
    tool: "mdutil",
    commands: {
      read: "mdutil -s {{volume}}",
      set: "sudo mdutil -i {{state}} {{volume}}",
    },
    applyAction: "none",
    requiresSudo: true,
    riskLevel: "caution",
    showInDefaultView: false,
    notes: "Use state=on or off. For all volumes use -a.",
  },
  {
    id: "spotlight.indexing-toggle-all",
    title: "Spotlight indexing state (all volumes)",
    category: "Spotlight",
    tool: "mdutil",
    commands: {
      read: "mdutil -sa",
      set: "sudo mdutil -a -i {{state}}",
    },
    applyAction: "none",
    requiresSudo: true,
    riskLevel: "danger",
    showInDefaultView: false,
    notes: "Use state=on or off.",
  },
  {
    id: "spotlight.rebuild-index",
    title: "Rebuild Spotlight index",
    category: "Spotlight",
    tool: "mdutil",
    commands: {
      read: "mdutil -s {{volume}}",
      set: "sudo mdutil -E {{volume}}",
    },
    applyAction: "none",
    requiresSudo: true,
    riskLevel: "caution",
    showInDefaultView: false,
  },
  {
    id: "softwareupdate.list",
    title: "List available software updates",
    category: "Software Update",
    tool: "softwareupdate",
    commands: {
      read: "softwareupdate -l",
      set: "softwareupdate -l",
    },
    applyAction: "none",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: true,
  },
  {
    id: "softwareupdate.install-all",
    title: "Install all software updates",
    category: "Software Update",
    tool: "softwareupdate",
    commands: {
      read: "softwareupdate -l",
      set: "sudo softwareupdate -ia",
    },
    applyAction: "reboot",
    requiresSudo: true,
    riskLevel: "danger",
    showInDefaultView: false,
  },
  {
    id: "softwareupdate.schedule",
    title: "Automatic update schedule",
    category: "Software Update",
    tool: "softwareupdate",
    commands: {
      read: "softwareupdate --schedule",
      set: "sudo softwareupdate --schedule {{state}}",
    },
    applyAction: "none",
    requiresSudo: true,
    riskLevel: "safe",
    showInDefaultView: true,
    notes: "Use state=on or off.",
  },
  {
    id: "softwareupdate.install-rosetta",
    title: "Install Rosetta 2",
    category: "Software Update",
    tool: "softwareupdate",
    commands: {
      read: "softwareupdate --history 2>/dev/null | grep -i rosetta || true",
      set: "softwareupdate --install-rosetta --agree-to-license",
    },
    applyAction: "none",
    requiresSudo: false,
    riskLevel: "safe",
    showInDefaultView: false,
    notes: "Apple Silicon only.",
  },
];
